--
-- PostgreSQL database dump
--

\restrict YPjoikuj78BCudyUf6AMMxaSgRuUdjItG9qrybdYDS5wWYJxwxp77uVQa554xrp

-- Dumped from database version 16.11
-- Dumped by pg_dump version 16.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: conge; Type: TABLE; Schema: public; Owner: laurent
--

CREATE TABLE public.conge (
    id integer NOT NULL,
    date_debut date NOT NULL,
    date_fin date NOT NULL,
    date_reponse date,
    date_demande date NOT NULL,
    commentaire text,
    commentaire_demandeur text,
    decision character varying(255) NOT NULL,
    demandeur_id integer NOT NULL,
    valideur_id integer,
    type_id integer NOT NULL
);


ALTER TABLE public.conge OWNER TO laurent;

--
-- Name: conge_id_seq; Type: SEQUENCE; Schema: public; Owner: laurent
--

ALTER TABLE public.conge ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conge_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: laurent
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO laurent;

--
-- Name: messenger_messages; Type: TABLE; Schema: public; Owner: laurent
--

CREATE TABLE public.messenger_messages (
    id bigint NOT NULL,
    body text NOT NULL,
    headers text NOT NULL,
    queue_name character varying(190) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    available_at timestamp(0) without time zone NOT NULL,
    delivered_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


ALTER TABLE public.messenger_messages OWNER TO laurent;

--
-- Name: messenger_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: laurent
--

ALTER TABLE public.messenger_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messenger_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role; Type: TABLE; Schema: public; Owner: laurent
--

CREATE TABLE public.role (
    id integer NOT NULL,
    nom character varying(255) NOT NULL,
    droit character varying(255) NOT NULL
);


ALTER TABLE public.role OWNER TO laurent;

--
-- Name: role_id_seq; Type: SEQUENCE; Schema: public; Owner: laurent
--

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: type_conges; Type: TABLE; Schema: public; Owner: laurent
--

CREATE TABLE public.type_conges (
    id integer NOT NULL,
    nom character varying(255) NOT NULL,
    jours_an integer NOT NULL,
    couleur character varying(255) NOT NULL,
    remuneration boolean NOT NULL
);


ALTER TABLE public.type_conges OWNER TO laurent;

--
-- Name: type_conges_id_seq; Type: SEQUENCE; Schema: public; Owner: laurent
--

ALTER TABLE public.type_conges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.type_conges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: laurent
--

CREATE TABLE public."user" (
    id integer NOT NULL,
    nom character varying(255) NOT NULL,
    prenom character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    type_contrat character varying(255) NOT NULL,
    role_id integer NOT NULL
);


ALTER TABLE public."user" OWNER TO laurent;

--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: laurent
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: conge; Type: TABLE DATA; Schema: public; Owner: laurent
--

COPY public.conge (id, date_debut, date_fin, date_reponse, date_demande, commentaire, commentaire_demandeur, decision, demandeur_id, valideur_id, type_id) FROM stdin;
\.


--
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: laurent
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
DoctrineMigrations\\Version20260324173754	2026-03-24 17:38:07	10
DoctrineMigrations\\Version20260324174005	2026-03-24 17:40:07	3
DoctrineMigrations\\Version20260324174516	2026-03-24 17:45:21	13
DoctrineMigrations\\Version20260324175556	2026-03-24 17:55:59	7
DoctrineMigrations\\Version20260324175841	2026-03-24 17:58:44	3
DoctrineMigrations\\Version20260324180400	2026-03-24 18:04:05	1
\.


--
-- Data for Name: messenger_messages; Type: TABLE DATA; Schema: public; Owner: laurent
--

COPY public.messenger_messages (id, body, headers, queue_name, created_at, available_at, delivered_at) FROM stdin;
\.


--
-- Data for Name: role; Type: TABLE DATA; Schema: public; Owner: laurent
--

COPY public.role (id, nom, droit) FROM stdin;
1	ROLE_USER	ROLE_USER
2	ROLE_ADMIN	ROLE_ADMIN
3	ROLE_MANAGER	ROLE_MANAGER
\.


--
-- Data for Name: type_conges; Type: TABLE DATA; Schema: public; Owner: laurent
--

COPY public.type_conges (id, nom, jours_an, couleur, remuneration) FROM stdin;
2	RTT	10	BLEU	t
1	Congé payé	25	VERT	t
3	Sans solde	99	ROUGE	f
4	Maladie	0	JAUNE	t
\.


--
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: laurent
--

COPY public."user" (id, nom, prenom, password, email, type_contrat, role_id) FROM stdin;
19	test	manag	$2y$13$gSn6FJaP47nkf2BrsbHqV.zxDTjhGQXAji7fgydDqrnasWpAS5xTW	testmanag@g	CDI	1
18	test	admin	$2y$13$.0Buy4YA3AcBrzrSJuO4XOaCq9UCHZZFYHmyNF/UEFYn0uj3HLQg2	testadmin@g	CDI	2
17	test	user	$2y$13$Me/K/i3d5GefHT5xmAfyouRYlYwemGd6xnj0UUAHy7ijTqsGDpO9S	usertest@g	CDI	1
\.


--
-- Name: conge_id_seq; Type: SEQUENCE SET; Schema: public; Owner: laurent
--

SELECT pg_catalog.setval('public.conge_id_seq', 1, false);


--
-- Name: messenger_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: laurent
--

SELECT pg_catalog.setval('public.messenger_messages_id_seq', 1, false);


--
-- Name: role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: laurent
--

SELECT pg_catalog.setval('public.role_id_seq', 3, true);


--
-- Name: type_conges_id_seq; Type: SEQUENCE SET; Schema: public; Owner: laurent
--

SELECT pg_catalog.setval('public.type_conges_id_seq', 4, true);


--
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: laurent
--

SELECT pg_catalog.setval('public.user_id_seq', 20, true);


--
-- Name: conge conge_pkey; Type: CONSTRAINT; Schema: public; Owner: laurent
--

ALTER TABLE ONLY public.conge
    ADD CONSTRAINT conge_pkey PRIMARY KEY (id);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: laurent
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: messenger_messages messenger_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: laurent
--

ALTER TABLE ONLY public.messenger_messages
    ADD CONSTRAINT messenger_messages_pkey PRIMARY KEY (id);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: laurent
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- Name: type_conges type_conges_pkey; Type: CONSTRAINT; Schema: public; Owner: laurent
--

ALTER TABLE ONLY public.type_conges
    ADD CONSTRAINT type_conges_pkey PRIMARY KEY (id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: laurent
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: idx_2ed89348780262a7; Type: INDEX; Schema: public; Owner: laurent
--

CREATE INDEX idx_2ed89348780262a7 ON public.conge USING btree (valideur_id);


--
-- Name: idx_2ed8934895a6ee59; Type: INDEX; Schema: public; Owner: laurent
--

CREATE INDEX idx_2ed8934895a6ee59 ON public.conge USING btree (demandeur_id);


--
-- Name: idx_2ed89348c54c8c93; Type: INDEX; Schema: public; Owner: laurent
--

CREATE INDEX idx_2ed89348c54c8c93 ON public.conge USING btree (type_id);


--
-- Name: idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750; Type: INDEX; Schema: public; Owner: laurent
--

CREATE INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON public.messenger_messages USING btree (queue_name, available_at, delivered_at, id);


--
-- Name: idx_8d93d649d60322ac; Type: INDEX; Schema: public; Owner: laurent
--

CREATE INDEX idx_8d93d649d60322ac ON public."user" USING btree (role_id);


--
-- Name: conge fk_2ed89348780262a7; Type: FK CONSTRAINT; Schema: public; Owner: laurent
--

ALTER TABLE ONLY public.conge
    ADD CONSTRAINT fk_2ed89348780262a7 FOREIGN KEY (valideur_id) REFERENCES public."user"(id);


--
-- Name: conge fk_2ed8934895a6ee59; Type: FK CONSTRAINT; Schema: public; Owner: laurent
--

ALTER TABLE ONLY public.conge
    ADD CONSTRAINT fk_2ed8934895a6ee59 FOREIGN KEY (demandeur_id) REFERENCES public."user"(id);


--
-- Name: conge fk_2ed89348c54c8c93; Type: FK CONSTRAINT; Schema: public; Owner: laurent
--

ALTER TABLE ONLY public.conge
    ADD CONSTRAINT fk_2ed89348c54c8c93 FOREIGN KEY (type_id) REFERENCES public.type_conges(id);


--
-- Name: user fk_8d93d649d60322ac; Type: FK CONSTRAINT; Schema: public; Owner: laurent
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT fk_8d93d649d60322ac FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- PostgreSQL database dump complete
--

\unrestrict YPjoikuj78BCudyUf6AMMxaSgRuUdjItG9qrybdYDS5wWYJxwxp77uVQa554xrp

