<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260601121346 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE obtention_diplome (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_obtention DATE NOT NULL, utilisateur_id INT NOT NULL, diplome_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F09CD140FB88E14F ON obtention_diplome (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_F09CD14026F859E2 ON obtention_diplome (diplome_id)');
        $this->addSql('ALTER TABLE obtention_diplome ADD CONSTRAINT FK_F09CD140FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE obtention_diplome ADD CONSTRAINT FK_F09CD14026F859E2 FOREIGN KEY (diplome_id) REFERENCES diplome (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE obtention_diplome DROP CONSTRAINT FK_F09CD140FB88E14F');
        $this->addSql('ALTER TABLE obtention_diplome DROP CONSTRAINT FK_F09CD14026F859E2');
        $this->addSql('DROP TABLE obtention_diplome');
    }
}
